#!/bin/sh
# Generates the Swift source that embeds the boattools version string.
#
# Resolution order (first match wins):
#   1. $BOATTOOLS_VERSION         explicit override — the release CI sets the tag
#   2. exact git tag on HEAD      a tagged release, e.g. "1.2"
#   3. dev-<ddMMyy> of the commit any other build, e.g. "dev-070625"
#   4. "unknown"                  no git metadata available (e.g. source tarball)
#
# The generated file is git-ignored and rewritten on every build; it is never
# committed. Releases get a reproducible tag, day-to-day builds a dated marker.
set -eu

OUT="${1:?usage: version.sh <output-file>}"

if [ -n "${BOATTOOLS_VERSION:-}" ]; then
    VERSION="$BOATTOOLS_VERSION"
elif TAG=$(git describe --tags --exact-match 2>/dev/null); then
    VERSION="$TAG"
elif DATE=$(git log -1 --format=%cd --date=format:%d%m%y 2>/dev/null); then
    VERSION="dev-$DATE"
    # Flag an uncommitted working tree so a local build is never mistaken for a
    # clean checkout.
    if ! git diff --quiet 2>/dev/null || ! git diff --cached --quiet 2>/dev/null; then
        VERSION="$VERSION-dirty"
    fi
else
    VERSION="unknown"
fi

CONTENT="// Generated by Scripts/version.sh — do not edit, do not commit.
enum ToolVersion { static let current = \"$VERSION\" }"

# Rewrite only when the value changes, so SwiftPM does not recompile needlessly.
OLD=$(cat "$OUT" 2>/dev/null || true)
if [ "$CONTENT" != "$OLD" ]; then
    mkdir -p "$(dirname "$OUT")"
    printf '%s\n' "$CONTENT" > "$OUT"
    echo "version.sh: $VERSION"
fi
